add tokyo-day theme & add contributor (README.md)
Ashutosh00710/github-readme-activity-graph pull request #148
Opened 2022-09-26 07:44 UTC by tranthaituananh

### All Submissions

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

2022-09-28 05:03 UTC, Ashutosh00710 requested changes
Can you please remove this theme from `README.md`? 
Just keep the image link in `THEMES.md` only

2022-09-30 02:48 UTC, tranthaituananh commented
I removed it from README.md

2022-10-01 02:06 UTC, Ashutosh00710 approved these changes

2022-10-01 02:06 UTC, merged

2022-10-01 02:07 UTC, Ashutosh00710 commented
Thank You for the contribution @tranthaituananh 🚀