Hello, I had made all the required cheanges in the footer, please hav…
Ashutosh00710/github-readme-activity-graph pull request #151
Opened 2022-10-02 21:17 UTC by AbhishekTiwari23

…e a look on that.

### All Submissions

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

2022-10-02 21:21 UTC, AbhishekTiwari23 commented
![image](https://user-images.githubusercontent.com/97469132/193476714-e76c1c59-6b00-43f5-85f3-ab6efbedbdac.png)
I have made all the required footer changes, making it more attractive and eye-catching.
Added social Icons.
I added the Hover effect in each incone.
Heighleted More Info line.

2022-10-03 19:08 UTC, AbhishekTiwari23 commented
Please make a response.

2022-10-05 08:46 UTC, Kshitij978 requested changes
Hi @AbhishekTiwari23 thanks for the effort. Nice hover effect 👍✨I have suggested few changes to be made before finally merging this PR. 

- Please delete the [.DS_Store](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86) & [github-readme-activity-graph Submodule](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151/files#diff-bb6a6a9d2a3f8829c84b5a3d99e120f8334975e802e7096466045bf28e6e9910) from the commit.

- Let's don't use any **social icons** for now as we don't have any socials for this project yet. You can keep your styling only on the **GitHub icon** after removing everything related to social icon and after applying the suggested changes.

2022-10-05 08:46 UTC, Kshitij978 commented on styles.css
> +}
Let's don't use this color on GitHub icon as it doesn't fit well with the whole theme of the website. We can just scale on hover without changing the color.

2022-10-05 08:46 UTC, Kshitij978 commented on styles.css
>  }
```suggestion
.link:hover i {
  transform: scale(1.05);
}
```

2022-10-05 09:29 UTC, AbhishekTiwari23 commented
> Hi @AbhishekTiwari23 thanks for the effort. Nice hover effect 👍✨I have suggested few changes to be made before finally merging this PR.
> 
> * Please delete the [.DS_Store](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86) & [github-readme-activity-graph Submodule](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151/files#diff-bb6a6a9d2a3f8829c84b5a3d99e120f8334975e802e7096466045bf28e6e9910) from the commit.
> * Let's don't use any **social icons** for now as we don't have any socials for this project yet. You can keep your styling only on the **GitHub icon** after removing everything related to social icon and after applying the suggested changes.

Is it fine ?

https://user-images.githubusercontent.com/97469132/194028403-3cab410d-6acc-439c-8649-58125ceb3f5e.mov

2022-10-05 09:39 UTC, AbhishekTiwari23 commented
@Kshitij978, sir, if you find it relevant, then please let me know so that I can make my first PR

2022-10-05 10:25 UTC, AbhishekTiwari23 commented
> @AbhishekTiwari23 everything looks great in the screen recording ✨
> 
> Please add these changes too starting from here: [#151 (comment)](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151#discussion_r987151544) to here: [#151 (comment)](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151#discussion_r987661842)
> 
> Also remove [this folder](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151/files#diff-bb6a6a9d2a3f8829c84b5a3d99e120f8334975e802e7096466045bf28e6e9910)
> 
> You can commit after doing all these changes. 👍
> 
> P.S. Let's call each other by name. We both are learners. 😄

Hello Bahiya, actually, by mistake, I deleted index.html while I was trying to delete the GitHub-readme-activity-graph submodule file. I tried to delete it, but it is not opening in GitHub I can delete it in my vs code. Can you Please guide me and please check whether I made a blunder or not? I have been using GitHub for the last few days, so I have less knowledge regarding all this. And apologise for my mistake once again

2022-10-05 11:34 UTC, Kshitij978 commented
> > @AbhishekTiwari23 everything looks great in the screen recording ✨
> > Please add these changes too starting from here: [#151 (comment)](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151#discussion_r987151544) to here: [#151 (comment)](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151#discussion_r987661842)
> > Also remove [this folder](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/151/files#diff-bb6a6a9d2a3f8829c84b5a3d99e120f8334975e802e7096466045bf28e6e9910)
> > You can commit after doing all these changes. 👍
> > P.S. Let's call each other by name. We both are learners. 😄
> 
> Hello Bahiya, actually, by mistake, I deleted index.html while I was trying to delete the GitHub-readme-activity-graph submodule file. I tried to delete it, but it is not opening in GitHub I can delete it in my vs code. Can you Please guide me and please check whether I made a blunder or not? I have been using GitHub for the last few days, so I have less knowledge regarding all this. And apologise for my mistake once again


@AbhishekTiwari23  Changes are looking great now 🎉.  Coming to the submodule you can:

**##Solution1**
- Try deleting the submodule from your local system then commit and make PR.

**##Solution2**
_**If the above solution doesn't work then please do the following:**_

1. Save a copy of these changes till now (`index.html`, `style.css`) at some different location on your system
2. Delete the clone of this repo from your system after backing up the changes
3. Delete your fork of this Repo from your GitHub
4. Start fresh by fork and clone
5. Include your changes to the freshly cloned repo. 

NOTE: **If you have to apply Solution2 then please _close this PR_ and create a fresh PR and mention the reference to this PR & a reference to the original issue in your _NEW PR_**


P.S. It's all fine don't worry you didn't break anything. You will get everything with time and practice ✨ You can watch tutorials and read articles for best practices. Keep grinding 💪

2022-10-05 21:19 UTC, closed without merging