Deploy on Vercel
Ashutosh00710/github-readme-activity-graph pull request #195
Opened 2023-04-29 04:17 UTC by fabianocouto

### Description

It just creates a vercel.json to deploy the project on Vercel.

### All Submissions

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions

1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

2023-04-29 14:12 UTC, Ashutosh00710 requested changes
Hi @fabianocouto, thank you for your pull request. I have reviewed your PR and I have a suggestion. **Could you please add instructions for Vercel deployment using the Vercel deployment button in the `README.md` file**? This will make it easier for users to deploy the project with just one click. Thank you for your contribution 🚀

2023-04-29 18:19 UTC, mdmuhtasimfuadfahim approved these changes

2023-04-30 03:07 UTC, fabianocouto commented
> Hi @fabianocouto, thank you for your pull request. I have reviewed your PR and I have a suggestion. **Could you please add instructions for Vercel deployment using the Vercel deployment button in the `README.md` file**? This will make it easier for users to deploy the project with just one click. Thank you for your contribution rocket

Hi, @Ashutosh00710 !
Just to let you know that the instructions were included in the readme as requested. ;)

2023-04-30 05:08 UTC, Ashutosh00710 approved these changes
I have reviewed the changes and everything looks good to me. I am merging it to the main branch. @fabianocouto , Thank you for your valuable contribution. 🚀

2023-04-30 05:09 UTC, merged